MvcOdevIntProgramciligi/Controllers/DersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcOdevIntProgramciligi.Models.Relationships;
using MvcOdevIntProgramciligi.Models;

namespace MvcOdevIntProgramciligi.Controllers
{
    public class DersController : Controller
    {
        public IActionResult Index()
        {
            using (var ctx = new OkulDBContext())
            {
                var lst = ctx.Dersler.ToList();
                return View(lst);
            }
        }

        [HttpGet]
        public IActionResult AddDers()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddDers(Ders ders)
        {
            if (ders != null)
            {
                using (var ctx = new OkulDBContext())
                {
                    ctx.Dersler.Add(ders);
                    ctx.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        public IActionResult EditDers(int id)
        {
            using (var ctx = new OkulDBContext())
            {
                var ders = ctx.Dersler.Find(id);
                return View(ders);
            }
        }

        [HttpPost]
        public IActionResult EditDers(Ders ders)
        {
            if (ders != null)
            {
                using (var ctx = new OkulDBContext())
                {
                    ctx.Entry(ders).State = EntityState.Modified;
                    ctx.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        public IActionResult DeleteDers(int id)
        {
            using (var ctx = new OkulDBContext())
            {
                var ders = ctx.Dersler.Find(id);
                if (ders != null)
                {
                    ctx.Dersler.Remove(ders);
                    ctx.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        public IActionResult KayitliOgrenciler(int id)
        {
            using (var ctx = new OkulDBContext())
            {
                var ders = ctx.Dersler.Include(d => d.OgrenciDersler!).ThenInclude(od => od.Ogrenci!).FirstOrDefault(d => d.Dersid == id);
                if (ders == null)
                {
                    return NotFound();
                }

                if (ders.OgrenciDersler == null)
                {
                    ders.OgrenciDersler = new List<OgrenciDers>();
                }

                return View(ders);
            }
        }
    }
}

MvcOdevIntProgramciligi/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcOdevIntProgramciligii.Models.Relationships;
using MvcOdevIntProgramciligi.Models;

namespace MvcOdevIntProgramciligi.Controllers
{
    public class StudentController : Controller
    {

        public IActionResult Index()
        {
            using (var ctx = new OkulDBContext())
            {
                var lst = ctx.Ogrenciler.ToList();
                return View(lst);

            }
        }


        [HttpGet] //Bunu default olarak yazmaya gerek yok
        public IActionResult AddStudent()
        {

            return View();
        }

        //Veritabanına inse işlemi yapıyoruz bu gibi işlemler post ile yapılır.
        [HttpPost] //Bunu yazmak zorunlu postlar.
        public IActionResult AddStudent(Ogrenci ogr)
        {
            if (ogr != null)
            {
                using (var ctx = new OkulDBContext())
                {
                    ctx.Ogrenciler.Add(ogr);
                    ctx.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }
        public IActionResult EditStudent(int id)
        {
            using (var ctx = new OkulDBContext())
            {
                var ogr = ctx.Ogrenciler.Find(id);

                return View(ogr);
            }
        }

        [HttpPost]
        public IActionResult EditStudent(Ogrenci ogr)
        {
            if (ogr != null)
            {
                using (var ctx = new OkulDBContext())
                {
                    ctx.Entry(ogr).State = EntityState.Modified;
                    ctx.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        public IActionResult DeleteStudent(int id)
        {
            using (var ctx = new OkulDBContext())
            {
                var ogr = ctx.Ogrenciler.Find(id);
                if (ogr != null)
                {
                    ctx.Ogrenciler.Remove(ogr);
                    ctx.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }



        // Öğrencinin aldığı dersleri göster
        public IActionResult OgrenciDersleri(int id)
        {
            using (var ctx = new OkulDBContext())
            {
                var ogrenci = ctx.Ogrenciler.Include(o => o.OgrenciDersler!).ThenInclude(od => od.Ders).FirstOrDefault(o => o.Ogrenciid == id);

                return View(ogrenci);
            }
        }

        // Öğrenciye ders ekle
        [HttpGet]
        public IActionResult AddDersForOgrenci(int studentId)
        {
            using (var ctx = new OkulDBContext())
            {
                var dersler = ctx.Dersler.ToList();
                var ogrenciDersler = ctx.OgrenciDersler.Where(od => od.Ogrenciid == studentId).Select(od => od.Dersid).ToList();
                var AktifDersler = dersler.Where(d => !ogrenciDersler.Contains(d.Dersid)).ToList();

                ViewBag.StudentId = studentId;
                return View(AktifDersler);
            }
        }


        [HttpPost]
        public IActionResult AddDersForOgrenci(int studentId, List<int> dersIds)
        {
            using (var ctx = new OkulDBContext())
            {
                var mevcutDersId = ctx.OgrenciDersler.Where(od => od.Ogrenciid == studentId).Select(od => od.Dersid).ToList();
                var yeniDersId = dersIds.Except(mevcutDersId).ToList();

                foreach (var dersId in yeniDersId)
                {
                    var ogrenciDers = new OgrenciDers
                    {
                        Ogrenciid = studentId,
                        Dersid = dersId
                    };
                    ctx.OgrenciDersler.Add(ogrenciDers);
                }
                ctx.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

MvcOdevIntProgramciligi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcOdevIntProgrmciligi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcOdevIntProgrmciligi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-secondary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sefa Demirkaya</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="Index" asp-controller="Student">Öğrenci İşlemleri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="Index" asp-controller="Ders">Ders İşlemleri</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - İnternet Programcılığı MVC sefa - <a href="https://github.com/sefademirkaya1/" target="_blank">GitHub</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>